# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Klein Visual: Exceptional Designs"
description: >-
  Klein Visual is the design portfolio and freelance business
  website of David Klein, a Carroll County, Maryland Multimedia
  Designer. We can create something exceptional together!
email: hi@kleinvisual.com
logo: img/kv-logo-full-color.png
social: 
    name: Klein Visual
    links:
      - https://www.instagram.com/kleinvisual/
      - https://www.youtube.com/channel/UCt5qUGnBGI1bgmlbvDcKt1g
baseurl: ""
url: "https://kleinvisual.com"
google_site_verification: jLURuYtb2QX7ci4rvZEu2MjOvHknFe8YRfoLv1s_zXU
lang: en_US
github_username:  "devjklein"

collections:
  design:
    output: true
    permalink: portfolio/:collection/:path
  computer-graphics:
    output: true
    permalink: portfolio/:collection/:path
    
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
      comments: "true"
      permalink: blog/:path
  - scope:
      path: ""
      type: "design"
    values:
      layout: "portfolio-page"
      comments: "true"
  - scope:
      path: ""
      type: "computer-graphics"
    values:
      layout: "portfolio-page"
      comments: "true"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
